import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "monospace"
style = "JetBrainsMono Nerd Font"
